### ISSUE TITLE
Copy button doesn't change text when generating another secret

### ISSUE THREAD

**Issue by milgner** [keedrop/keedrop#56]
When I create and encode another secret, the button still says "Copied" even though it just generated another URL.

**Comment by pke** [comment]
Thanks for reporting.

Notes to me:

1. Write an e2e test, expecting the button switch text
2. see it fail
3. implement fix

**Comment by pke** [comment]
Not so easy to test because cypress can't create native events yet, so the copy command does not work.
https://github.com/cypress-io/cypress/issues/2851
