### ISSUE TITLE
Improve mozilla observatory scoring

### ISSUE THREAD

**Issue by pke** [keedrop/keedrop#58]
Should be an "A" but is a "D"
https://observatory.mozilla.org/analyze/keedrop.com

## Test Scores

|Test | Pass | Score | Reason |
|-----|------|-------|--------|
Content Security Policy |   | -20 | Content Security Policy (CSP) implemented unsafely.This includes 'unsafe-inline' or data: inside script-src, overly broad sources such as https: inside object-src or script-src, or not restricting the sources for object-src or script-src. |  
Cookies |   | 0 | No cookies detected |  
Cross-origin Resource Sharing |   | 0 | Content is not visible via cross-origin resource sharing (CORS) files or headers |  
HTTP Public Key Pinning |   | 0 | HTTP Public Key Pinning (HPKP) header not implemented (optional) |  
HTTP Strict Transport Security |   | -20 | HTTP Strict Transport Security (HSTS) header not implemented |  
Redirection |   | 0 | Initial redirection is to HTTPS on same host, final destination is HTTPS |  
Referrer Policy |   | 0 | Referrer-Policy header not implemented (optional) |  
Subresource Integrity |   | 0 | Subresource Integrity (SRI) not implemented, but all scripts are loaded from a similar origin |  
X-Content-Type-Options |   | -5 | X-Content-Type-Options header not implemented |  
X-Frame-Options |   | -20 | X-Frame-Options (XFO) header not implemented |  
X-XSS-Protection |   | -10 | X-XSS-Protection header not implemented

## Failed CSP 

| Test |
|-|
|Blocks execution of inline JavaScript by not allowing 'unsafe-inline' inside script-src|
|Blocks execution of plug-ins, using object-src restrictions|
|Blocks inline styles by not allowing 'unsafe-inline' inside style-src|
|Clickjacking protection, using frame-ancestors|
|Deny by default, using default-src 'none'|
|Restricts use of the <base> tag by using base-uri 'none', base-uri 'self', or specific origins|
|Restricts where <form> contents may be submitted by using form-action 'none', form-action 'self', or specific URIs|
|Uses CSP3's 'strict-dynamic' directive to allow dynamic script loading (optional)|

**Comment by milgner** [comment]
A+ now
