### ISSUE TITLE
When on imprint, changing locale does not work

### ISSUE THREAD

**Issue by milgner** [keedrop/keedrop#67]
The path is `/impressum` for de but `/imprint` for en. Thus, replacing the locale in the path does not work.

**Comment by pke** [comment]
Right, that seems to be indeed a bug I missed. Should write a e2e for it as a regression test.
I thought I had tested that. Probably the links are wrongly composed somewhere.

**Comment by pke** [comment]
https://github.com/keedrop/keedrop/blob/master/site/_layouts/default.html#L32
