### ISSUE TITLE
Remove invalid Feature-Policy: speaker header

### ISSUE THREAD

**Issue by pke** [keedrop/keedrop#73]
Chrome complains: `Error with Feature-Policy header: Unrecognized feature: 'speaker'.`
And I can't find this header in the[ mozilla "Feature-Policy" docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy) either.

**Comment by milgner** [comment]
Done ✅

**Comment by pke** [comment]
Is master also deployed?
