### ISSUE TITLE
DNSSec fails?

### ISSUE THREAD

**Issue by pke** [keedrop/keedrop#83]
https://dnssec-analyzer.verisignlabs.com/keedrop.de shows several fails?

**Comment by milgner** [comment]
As Porkbun doesn't support .de domains yet, the domain is still hosted at AWS/Route53 and I hadn't set up DNSSEC there yet. Luckily the costs are negligible so I set it up now. DS records are still propagating right now and they should become visible any minute now.

**Comment by pke** [comment]
Nice. Thanks. Chrome on ios doesn't handle the analyse site well. It stalls. Safari works and all is green!
